// <auto-generated />
namespace Adventurous.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedIsFreeproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedIsFreeproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201604090112199_added IsFree property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
